/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_24 (coord B6), P0_24/SJ7[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIO0_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIO0_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO0_GPIO_PIN 24U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_GPIO0_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPIO0_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO0_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO0_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT4_1 (coord P2), P4_1/J8[3]/SJ15[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ESP_OLD_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ESP_OLD_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ESP_OLD_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT4_0 (coord P1), P4_0/J8[4]/SJ14[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ESP_OLD2_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ESP_OLD2_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ESP_OLD2_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_3 (coord D16), P3_3/J9[19]/SJ12[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ESP_TX_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ESP_TX_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ESP_TX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_2 (coord D15), P3_2/J9[20]/J7[8]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ESP_RX_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ESP_RX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ESP_RX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
