/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u        /*!<@brief Input Buffer Enable: Enables */
#define PORT5_PCR_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIO_27_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIO_27_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO_27_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_GPIO_27_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPIO_27_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_27_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_27_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT0_26 (coord F10), P0_26/J2[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GPIO_26_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GPIO_26_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO_26_GPIO_PIN 26U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_GPIO_26_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPIO_26_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_26_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_26_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_0 (coord C6), P1_0/J5[6]/J2[17]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ESP_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ESP_RX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ESP_RX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT1_1 (coord C5), P1_1/J5[5]/J2[15]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ESP_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ESP_TX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ESP_TX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT0_28 (coord E8), P0_28/J2[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTOR2_IN3_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_IN3_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_MOTOR2_IN3_GPIO_PIN 28U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MOTOR2_IN3_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR2_IN3_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_IN3_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR2_IN3_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT0_31 (coord D7), P0_31/J1[16]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MOTOR2_IN4_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_IN4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_MOTOR2_IN4_GPIO_PIN 31U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MOTOR2_IN4_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR2_IN4_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR2_IN4_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR2_IN4_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT0_24 (coord B6), P0_24/SJ7[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPIO0_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO0_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO0_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT5_8 (coord L14), P5_8/U9[19]/J9[31]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_senzor_trig_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_senzor_trig_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_senzor_trig_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_senzor_trig_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_senzor_trig_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_senzor_trig_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_senzor_trig_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT5_9 (coord M14), P5_9/J9[29]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_senzor_echo_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_senzor_echo_GPIO_PIN 9U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_senzor_echo_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_senzor_echo_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_senzor_echo_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_senzor_echo_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
